---
- name: add surfacelinux repo
  deb822_repository:
    name: surfacelinux
    types: deb
    enabled: true
    uris: https://pkg.surfacelinux.com/debian
    suites: release
    components: main
    signed_by: https://raw.githubusercontent.com/linux-surface/linux-surface/master/pkg/keys/surface.asc
    architectures: amd64

- name: update repositories
  apt: 
    update_cache: yes
    upgrade: safe
  changed_when: False

- name: install surface kernel
  apt:  
    name: 
      - linux-image-surface
      - linux-headers-surface
    state: latest

- name: install extra surface apps
  apt:  
    name: 
      - iptsd
      - surface-control
      - surface-dtx-daemon
      - libwacom-surface
    state: latest

- name: enable iptsd@dev-hidraw0.service
  systemd:
    name: 'iptsd@dev-hidraw0.service'
    enabled: yes

- name: enable surface-dtx-daemon service for main user
  file:
    src: /usr/lib/systemd/user/surface-dtx-userd.service
    path: "/home/{{ user }}/.config/systemd/user/default.target.wants/surface-dtx-userd.service"
    state: link
    owner: "{{ user }}"
    group: users

